---
title: "Eurovision"
author: "Oleksandra"
date: "2023-06-21"
output: html_document
---

Load packages

```{r}
library(dplyr)
library(ggplot2)
install.packages("remotes")
remotes::install_github("jimjam-slam/ggflags")
library(ggflags)
```

Load the data

```{r}
eurovision <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-17/eurovision.csv')
```

Review the data

```{r}
summary(eurovision)
head(eurovision)
glimpse(eurovision)

unique(eurovision$section)

eurovision_finals<-eurovision %>%
  filter(section == "grand-final" | section == "final" )
```

Prep flags

```{r}
flags<-eurovision_finals$country_emoji
flags_clean<-gsub(pattern = ":flag_", "",x=flags) %>% gsub(":","",.)
flags_clean[1:5]

eurovision_finals$flags_clean<-flags_clean

names(eurovision_finals)
```

Prep and Viz

```{r}
winners<-eurovision_finals %>%
  filter(winner == TRUE) %>%
  filter(year >= 1970) 


head(winners)
glimpse(winners)
ggplot(winners, aes(x = year, y = total_points)) + 
 ggflags::geom_flag(aes(country = flags_clean))

winners_plot<-ggplot(winners, aes(x = year, y = total_points)) + 
  geom_segment(aes(xend = year, yend = 0)) +
  geom_point(colour = "gold") + 
  geom_text(aes(label = artist), hjust = -0.1)+
  coord_flip()+
  labs(title = "Eurovision winners 1970-2022",
       caption = "MISDI code camp") +
  theme_minimal(base_family = "Arial", 
                base_size = 16)
winners_plot

ggsave(filename = "winners_plot.png", winners_plot,
       units = "px",width = 3000, height = 2750, bg = "white")

winners<-eurovision_finals %>%
  filter(winner == TRUE) %>%
  filter(year >= 1970) %>%
  filter(nchar(flags_clean) <=2)


head(winners)
glimpse(winners)
ggplot(winners, aes(x = year, y = total_points)) + 
 ggflags::geom_flag(aes(country = flags_clean))

winners_plot<-ggplot(winners, aes(x = year, y = total_points)) + 
  geom_segment(aes(xend = year, yend = 0)) +
  geom_flag(aes(country = flags_clean)) + 
  geom_text(aes(label = artist), hjust = -0.1)+
  coord_flip()+
  labs(title = "Eurovision winners 1970-2022",
       caption = "MISDI code camp") +
  theme_minimal(base_family = "Arial", 
                base_size = 16)
winners_plot

ggsave(filename = "winners_plot.png", winners_plot,
       units = "px",width = 3000, height = 2750, bg = "white")
```

