---
title: "GitHub"
author: "Oleksandra"
date: "2023-06-22"
output: html_document
---

```{r}
# load libraries (quietly stops all the messages appearing)
library(readr, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(DT, quietly = TRUE)

```

```{r}
# load imdb and bechdel
movies_imdb <- read_csv("https://raw.githubusercontent.com/andrewmoles2/rTrainIntroduction/main/r-data-wrangling-1/data/IMDb%20movies.csv")

bechdel <- read_csv("https://raw.githubusercontent.com/andrewmoles2/rTrainIntroduction/main/r-data-wrangling-1/data/raw_bechdel.csv")
```

```{r}
# fix imdb id key
movies_imdb$imdb_title_id <- parse_number(movies_imdb$imdb_title_id)

# join data (left join)
imdb_bechdel <- left_join(x = movies_imdb, y = bechdel,
                          by = c("imdb_title_id" = "imdb_id", "year", "title"))
```

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
```



```{r}
#Thriller

thriller_movies<-imdb_bechdel[str_detect(imdb_bechdel$genre, "Thriller"), ]

sorted_movies <- thriller_movies[order(thriller_movies$avg_vote, decreasing = TRUE), ]

sorted_movies

top_10_movies <- head(sorted_movies, 10)

top_10_movies


```

```{r}

#Graph
thriller_plot<-ggplot(top_10_movies, aes(x = title, y = avg_vote)) +
  geom_bar() + 
  coord_flip()

thriller_plot

food_co2 <- food_consumption %>% 
  group_by(country) %>% 
  summarise(co2 = sum(co2_emmission)) %>% 
  top_n(., 10, co2) %>% 
  arrange(co2) %>% 
  mutate(n = -4:5) %>% 
  rowwise() %>%
  mutate(
    x = list(c(-10, 0, 0, -10)),
    y = list(c(n*4 - 1.4, n*2 - 0.7, n*2 + 0.7, n*4 + 1.4))
  ) %>% 
  unnest(cols = c(x, y))
  
ggplot(food_co2) +
  geom_rect(aes(xmin = -42, ymin = n*4 - 1.4,
                xmax = -10, ymax = n*4 + 1.4), fill = "black", color = NA) +
  geom_polygon(aes(x, y, group = n), fill = "black", color = NA) +
  geom_rect(aes(xmin = 0, ymin = n*2 - 0.7,
                xmax = co2/25, ymax = n*2 + 0.7), fill = "black", color = NA) +
  geom_text(aes(-40.5, n*4, label = country), family = "Arial", color = "white", hjust = 0, size = 8.5, check_overlap = TRUE) +
  geom_text(aes(co2/25-1, n*2, label = co2), family = "Arial", color = "white", hjust = 1, size = 4, check_overlap = TRUE) +
  annotate("text", 85, 17, label = "Total food carbon footprint\nKg CO2/person/year", family = "IBM Plex Sans Bold", color = "black", hjust = 1, size = 13, lineheight = 0.9) +
  annotate("text", 1, -9.5, label = "Source: nu3 | Graphic: Georgios Karamanis", family = "IBM Plex Sans", color = "black", hjust = 0, size = 4, lineheight = 0.9) +
  scale_x_continuous(breaks = seq(0, 80, 20), labels = seq(0, 2000, 500)) +
  theme_minimal(base_family = "Arial") +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(family = "Arial", size = 12),
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_line(color = "black", size = 0.2),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.margin = margin(20, 20, 20, 20)
  ) 

ggsave(here::here("2020-week08", "plots", "food-consumption.png"), dpi = 320, width = 12, height = 8)


```






```{r}


# load imdb and bechdel
movies_imdb <- read_csv("https://raw.githubusercontent.com/andrewmoles2/rTrainIntroduction/main/r-data-wrangling-1/data/IMDb%20movies.csv")

bechdel <- read_csv("https://raw.githubusercontent.com/andrewmoles2/rTrainIntroduction/main/r-data-wrangling-1/data/raw_bechdel.csv")
```

```{r}
# fix imdb id key
movies_imdb$imdb_title_id <- parse_number(movies_imdb$imdb_title_id)

# join data (left join)
imdb_bechdel <- left_join(x = movies_imdb, y = bechdel,
                          by = c("imdb_title_id" = "imdb_id", "year", "title"))
```

```{r}
#Thriller

thriller_movies<-imdb_bechdel[str_detect(imdb_bechdel$genre, "Thriller"), ]

sorted_movies <- thriller_movies[order(thriller_movies$avg_vote, decreasing = TRUE), ]

sorted_movies

top_10_movies <- head(sorted_movies, 10)

top_10_movies
```


```{r}
library(tidyverse)
library(here)
library(ggflags)

# load imdb and bechdel
movies_imdb <- read_csv("https://raw.githubusercontent.com/andrewmoles2/rTrainIntroduction/main/r-data-wrangling-1/data/IMDb%20movies.csv")

bechdel <- read_csv("https://raw.githubusercontent.com/andrewmoles2/rTrainIntroduction/main/r-data-wrangling-1/data/raw_bechdel.csv")

# fix imdb id key
movies_imdb$imdb_title_id <- parse_number(movies_imdb$imdb_title_id)

# join data (left join)
imdb_bechdel <- left_join(x = movies_imdb, y = bechdel,
                          by = c("imdb_title_id" = "imdb_id", "year", "title"))



movie_github <- imdb_bechdel %>% 
  group_by(country) %>% 
  summarise( number_of_movies = sum(!is.na(title))) %>% 
  top_n(., 5, number_of_movies) %>% 
  arrange(number_of_movies) %>% 
  mutate(n = -2:2) %>% 
  rowwise() %>%
  mutate(
    x = list(c(-10, 0, 0, -10)),
    y = list(c(n*4 - 1.4, n*2 - 0.7, n*2 + 0.7, n*4 + 1.4))
  ) %>% 
  unnest(cols = c(x, y)) %>%
  mutate(rating_string = case_when(
    country == "USA" ~ "us",
    country == "India" ~ "in",
    country == "UK" ~ "gb",
    country == "Japan" ~ "jp",
    country == "France" ~ "fr"
  ))
  
movie_github_a<-ggplot(movie_github) +
  geom_rect(aes(xmin = -42, ymin = n*4 - 1.4,
                xmax = -10, ymax = n*4 + 1.4), fill = "#5465FF", color = NA) +
  geom_polygon(aes(x, y, group = n), fill = "#788BFF", color = NA) +
  geom_rect(aes(xmin = 0, ymin = n*2 - 0.7,
                xmax = number_of_movies/270, ymax = n*2 + 0.7), fill = "#9BB1FF", color = NA) +
  geom_flag(aes(x = -50, y = n * 4, country = rating_string), size = 15) +
  geom_text(aes(-40.5, n*4, label = country), family = "Arial", color = "white", hjust = 0, size = 11.5, check_overlap = TRUE) +
  geom_text(aes(number_of_movies/270-1, n*2, label = number_of_movies), family = "Arial", color = "white", hjust = 1, size = 8, check_overlap = TRUE) +
  annotate("text", 85, 17, label = "Total Number of Movies Per Country", family = "Arial", color = "#03045E", hjust = 1, size = 13, lineheight = 0.9) +
scale_x_continuous(breaks = seq(0, 80, 20), labels = seq(0, 2000, 500)) +
    labs( x = "Number of Movies",
       y = "Country") +
      
  theme_minimal(base_family = "Arial") +
  theme(
    axis.text.x = element_text(family = "Arial", size = 15),
    axis.text.y = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_line(color = "black", size = 0.2),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.margin = margin(20, 20, 40, 20),
     panel.background = element_rect(fill = "#E5C3D1"),
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
  ) 

movie_github_a


ggsave(filename = "movie_github_a16.png", movie_github_a,
       units = "px",width = 5000, height = 3000, bg = "white")






```

```


  
```

